// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpknthvoibtntmhslmfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwa250aHZvaWJ0bnRtaHNsbWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mjk4NDIsImV4cCI6MjA3MzQwNTg0Mn0.XbPuK-ESMR_HdPf8USRsLlzXeNQvaGMw333I0RqVYYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});